# Generated by Django 5.2.8 on 2025-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nivel',
            field=models.CharField(default=2, max_length=100, verbose_name='Nivel ingles'),
            preserve_default=False,
        ),
    ]
