# Generated by Django 5.2.8 on 2025-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0002_author_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Edad'),
        ),
    ]
