# Generated by Django 5.2.8 on 2026-01-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0003_alter_author_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título del libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HolaMundo.author')),
            ],
        ),
    ]
